# Generated by Django 4.2.13 on 2024-05-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsuploader', '0002_rename_record_url_callinfo_file_callinfo_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='callinfo',
            name='vote',
            field=models.IntegerField(blank=True, choices=[(1, 'Ужасно'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], null=True),
        ),
    ]
