# Generated by Django 4.2.13 on 2024-05-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsuploader', '0004_alter_callinfo_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callinfo',
            name='vote',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
