# Generated by Django 4.2.13 on 2024-06-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0006_auto_20240528_1411'),
        ('robot_vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrencyRobot',
            new_name='VacanciesRobot',
        ),
    ]
